"""Model inference endpoint.

Thin wrapper around ``src.eval``: ``make_env()``, ``run_inference()``,
``reconstruct_map()``, ``compute_diff_cells()``.

Models are pre-loaded at startup.  For dynamic study areas the env's
``self.data`` is replaced with the dataset generated by grid_service
so that ``augment_data`` / ``_get_obs`` operate on the correct grid.
"""

from functools import lru_cache
from pathlib import Path
from types import SimpleNamespace

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

import src.train as train_module
from src.config import ECO_VALUES
from src.eval import (
    build_value_vecs, make_env, run_inference,
    reconstruct_map, compute_diff_cells,
)
from src.utils import get_logger
from backend.formatting import build_results_json

logger = get_logger("infer_service", level="INFO")
router = APIRouter()

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

# (run_id, spatial_scale) per experiment — must match training configs
EXPERIMENTS = {
    "exp1": ("6f0ta58i", 0.0),
    "exp2": ("2sk0pnp3", 1.0),
    "exp3": ("pzy2mxod", 1.0),
}

REGEN_CROP_MULTIPLIER = 1.35

_models: dict = {}


def load_models():
    """Pre-load all MaskablePPO models at app startup.

    Follows the same pattern as ``eval.py:main()``:
    1. Set the train-module logger.
    2. ``build_value_vecs`` → populates ``ECO_MOD`` / ``ET_MOD`` globals.
    3. Create a dummy env (SB3 requires one) and load each model.
    """
    from sb3_contrib import MaskablePPO

    train_module.logger = get_logger("train", level="WARNING")
    build_value_vecs(use_et=False, assign_globals=True)

    for exp_id, (run_id, spatial_scale) in EXPERIMENTS.items():
        model_path = PROJECT_ROOT / "models" / run_id / "model.zip"
        if not model_path.exists():
            logger.warning(f"Model not found for {exp_id}: {model_path}")
            continue

        # eval.py pattern: dummy env → load model
        dummy_env = make_env(SimpleNamespace(spatial_scale=spatial_scale), "test_indices")
        model = MaskablePPO.load(str(model_path), env=dummy_env)
        _models[exp_id] = (model, spatial_scale)
        logger.info(f"Loaded model for {exp_id} (run {run_id})")

    logger.info(f"Models loaded: {list(_models.keys())}")


# ---------------------------------------------------------------------------
# Request model
# ---------------------------------------------------------------------------
class InferRequest(BaseModel):
    lat: float
    lng: float
    experiment: str


# ---------------------------------------------------------------------------
# Inference (cached)
# ---------------------------------------------------------------------------
@lru_cache(maxsize=32)
def _run_cached(lat_r: float, lng_r: float, experiment: str):
    """Run model inference following the ``eval.py:main()`` pattern:

    1. Get the dynamic dataset from grid_service.
    2. For each split: ``make_env`` → override ``env.data`` → ``run_inference``.
    3. ``reconstruct_map`` → ``compute_diff_cells`` → format JSON.
    """
    from backend.grid_service import get_cached_dataset

    model, spatial_scale = _models[experiment]
    dataset = get_cached_dataset(lat_r, lng_r)
    env_args = SimpleNamespace(spatial_scale=spatial_scale)

    # eval.py pattern: run both splits, merge results
    combined = {}
    for split in ("test_indices", "train_indices"):
        env = make_env(env_args, split)
        # Override env.data so augment_data / _get_obs use the dynamic grid
        # instead of the hardcoded rl_dataset.npz loaded in LandUseEnv.__init__
        env.data = dataset
        combined.update(
            run_inference(model, env, dataset, split, deterministic=True)
        )

    # eval.py: reconstruct_map + compute_diff_cells
    initial_obs, final_obs = reconstruct_map(dataset, combined)
    changed_cells = compute_diff_cells(initial_obs, final_obs, atol=1e-4)

    # ESV map (exp3 uses regenerative crop multiplier)
    esv_map = dict(ECO_VALUES)
    if experiment == "exp3":
        esv_map[5] = round(esv_map[5] * REGEN_CROP_MULTIPLIER)

    # formatting.py: assemble JSON response
    return build_results_json(experiment, initial_obs, final_obs, changed_cells, esv_map)


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------
@router.post("/infer")
def infer(req: InferRequest):
    if req.experiment not in EXPERIMENTS:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown experiment '{req.experiment}'. "
                   f"Choose from: {list(EXPERIMENTS.keys())}",
        )

    lat_r = round(req.lat, 6)
    lng_r = round(req.lng, 6)
    logger.info(f"Running inference for {req.experiment} at ({lat_r}, {lng_r})")
    return _run_cached(lat_r, lng_r, req.experiment)
